export const FETCH_FILMS_START = 'FETCH_FILMS_START';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAIL = 'FETCH_FILMS_FAIL';

export const UPDATE_DISPLAYED_FILMS = 'UPDATE_DISPLAYED_FILMS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ADD_TO_USER_QUEUE_START = 'ADD_TO_USER_QUEUE_START';
export const ADD_TO_USER_QUEUE_SUCCESS = 'ADD_TO_USER_QUEUE_SUCCESS';
export const ADD_TO_USER_QUEUE_FAIL = 'ADD_TO_USER_QUEUE_FAIL';

export const REMOVE_FROM_USER_QUEUE_START = 'REMOVE_FROM_USER_QUEUE_START';
export const REMOVE_FROM_USER_QUEUE_SUCCESS = 'REMOVE_FROM_USER_QUEUE_SUCCESS';
export const REMOVE_FROM_USER_QUEUE_FAIL = 'REMOVE_FROM_USER_QUEUE_FAIL';

export const FETCH_USER_QUEUE_START = 'FETCH_USER_QUEUE_START';
export const FETCH_USER_QUEUE_SUCCESS = 'FETCH_USER_QUEUE_SUCCESS';
export const FETCH_USER_QUEUE_FAIL = 'FETCH_USER_QUEUE_FAIL';

export const TOGGLE_ONLY_SHOW_QUEUE = 'TOGGLE_ONLY_SHOW_QUEUE';